# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 5120
    v.cpus = 4
  end

  config.vm.network "forwarded_port", guest: 9200, host: 9200 # Elasticsearch

  config.vm.provision :shell do |sh|
    sh.path = "sys/bare_bootstrap.sh"
    sh.privileged = true
  end

  config.vm.provision :shell do |sh|
    sh.path = "sys/bootstrap.sh"
    sh.privileged = false
  end

  config.vm.provision :file do |file|
    file.source =  "./logstash/weather.conf"
    file.destination = "weather.conf"
  end

end
